package com.bee.team.fastgo.model;

import com.alibaba.lava.base.LavaExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GitlabUserDoExample extends LavaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public GitlabUserDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGitlabUserNameIsNull() {
            addCriterion("gitlabUserName is null");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameIsNotNull() {
            addCriterion("gitlabUserName is not null");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameEqualTo(String value) {
            addCriterion("gitlabUserName =", value, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameNotEqualTo(String value) {
            addCriterion("gitlabUserName <>", value, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameGreaterThan(String value) {
            addCriterion("gitlabUserName >", value, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("gitlabUserName >=", value, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameLessThan(String value) {
            addCriterion("gitlabUserName <", value, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameLessThanOrEqualTo(String value) {
            addCriterion("gitlabUserName <=", value, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameLike(String value) {
            addCriterion("gitlabUserName like", value, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameNotLike(String value) {
            addCriterion("gitlabUserName not like", value, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameIn(List<String> values) {
            addCriterion("gitlabUserName in", values, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameNotIn(List<String> values) {
            addCriterion("gitlabUserName not in", values, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameBetween(String value1, String value2) {
            addCriterion("gitlabUserName between", value1, value2, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabUserNameNotBetween(String value1, String value2) {
            addCriterion("gitlabUserName not between", value1, value2, "gitlabUserName");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordIsNull() {
            addCriterion("gitlabPassword is null");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordIsNotNull() {
            addCriterion("gitlabPassword is not null");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordEqualTo(String value) {
            addCriterion("gitlabPassword =", value, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordNotEqualTo(String value) {
            addCriterion("gitlabPassword <>", value, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordGreaterThan(String value) {
            addCriterion("gitlabPassword >", value, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("gitlabPassword >=", value, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordLessThan(String value) {
            addCriterion("gitlabPassword <", value, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordLessThanOrEqualTo(String value) {
            addCriterion("gitlabPassword <=", value, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordLike(String value) {
            addCriterion("gitlabPassword like", value, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordNotLike(String value) {
            addCriterion("gitlabPassword not like", value, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordIn(List<String> values) {
            addCriterion("gitlabPassword in", values, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordNotIn(List<String> values) {
            addCriterion("gitlabPassword not in", values, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordBetween(String value1, String value2) {
            addCriterion("gitlabPassword between", value1, value2, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabPasswordNotBetween(String value1, String value2) {
            addCriterion("gitlabPassword not between", value1, value2, "gitlabPassword");
            return (Criteria) this;
        }

        public Criteria andGitlabNameIsNull() {
            addCriterion("gitlabName is null");
            return (Criteria) this;
        }

        public Criteria andGitlabNameIsNotNull() {
            addCriterion("gitlabName is not null");
            return (Criteria) this;
        }

        public Criteria andGitlabNameEqualTo(String value) {
            addCriterion("gitlabName =", value, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameNotEqualTo(String value) {
            addCriterion("gitlabName <>", value, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameGreaterThan(String value) {
            addCriterion("gitlabName >", value, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameGreaterThanOrEqualTo(String value) {
            addCriterion("gitlabName >=", value, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameLessThan(String value) {
            addCriterion("gitlabName <", value, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameLessThanOrEqualTo(String value) {
            addCriterion("gitlabName <=", value, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameLike(String value) {
            addCriterion("gitlabName like", value, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameNotLike(String value) {
            addCriterion("gitlabName not like", value, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameIn(List<String> values) {
            addCriterion("gitlabName in", values, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameNotIn(List<String> values) {
            addCriterion("gitlabName not in", values, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameBetween(String value1, String value2) {
            addCriterion("gitlabName between", value1, value2, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabNameNotBetween(String value1, String value2) {
            addCriterion("gitlabName not between", value1, value2, "gitlabName");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailIsNull() {
            addCriterion("gitlabEmail is null");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailIsNotNull() {
            addCriterion("gitlabEmail is not null");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailEqualTo(String value) {
            addCriterion("gitlabEmail =", value, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailNotEqualTo(String value) {
            addCriterion("gitlabEmail <>", value, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailGreaterThan(String value) {
            addCriterion("gitlabEmail >", value, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailGreaterThanOrEqualTo(String value) {
            addCriterion("gitlabEmail >=", value, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailLessThan(String value) {
            addCriterion("gitlabEmail <", value, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailLessThanOrEqualTo(String value) {
            addCriterion("gitlabEmail <=", value, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailLike(String value) {
            addCriterion("gitlabEmail like", value, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailNotLike(String value) {
            addCriterion("gitlabEmail not like", value, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailIn(List<String> values) {
            addCriterion("gitlabEmail in", values, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailNotIn(List<String> values) {
            addCriterion("gitlabEmail not in", values, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailBetween(String value1, String value2) {
            addCriterion("gitlabEmail between", value1, value2, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andGitlabEmailNotBetween(String value1, String value2) {
            addCriterion("gitlabEmail not between", value1, value2, "gitlabEmail");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdIsNull() {
            addCriterion("gitlabUserId is null");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdIsNotNull() {
            addCriterion("gitlabUserId is not null");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdEqualTo(Integer value) {
            addCriterion("gitlabUserId =", value, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdNotEqualTo(Integer value) {
            addCriterion("gitlabUserId <>", value, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdGreaterThan(Integer value) {
            addCriterion("gitlabUserId >", value, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("gitlabUserId >=", value, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdLessThan(Integer value) {
            addCriterion("gitlabUserId <", value, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("gitlabUserId <=", value, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdIn(List<Integer> values) {
            addCriterion("gitlabUserId in", values, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdNotIn(List<Integer> values) {
            addCriterion("gitlabUserId not in", values, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdBetween(Integer value1, Integer value2) {
            addCriterion("gitlabUserId between", value1, value2, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andGitlabUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("gitlabUserId not between", value1, value2, "gitlabUserId");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "Id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "Id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "Id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "Id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("GMT_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("GMT_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("GMT_CREATE =", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("GMT_CREATE <>", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("GMT_CREATE >", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE >=", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("GMT_CREATE <", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE <=", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("GMT_CREATE in", values, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("GMT_CREATE not in", values, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE between", value1, value2, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE not between", value1, value2, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("GMT_MODIFIED is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("GMT_MODIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("GMT_MODIFIED =", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <>", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("GMT_MODIFIED >", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED >=", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("GMT_MODIFIED <", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <=", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("GMT_MODIFIED in", values, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("GMT_MODIFIED not in", values, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED between", value1, value2, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED not between", value1, value2, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("MODIFIER =", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("MODIFIER <>", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("MODIFIER >", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIER >=", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("MODIFIER <", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("MODIFIER <=", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("MODIFIER in", values, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("MODIFIER not in", values, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("MODIFIER between", value1, value2, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("MODIFIER not between", value1, value2, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("MODIFIER like", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("MODIFIER not like", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("IS_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("IS_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("IS_DELETED =", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("IS_DELETED <>", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("IS_DELETED >", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETED >=", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("IS_DELETED <", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETED <=", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("IS_DELETED in", values, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("IS_DELETED not in", values, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("IS_DELETED between", value1, value2, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("IS_DELETED not between", value1, value2, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("IS_DELETED like", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("IS_DELETED not like", value, "IsDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_gitlab_user
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 04 14:37:49 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_gitlab_user
     *
     * @mbg.generated Tue Aug 04 14:37:49 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}