package com.bee.team.fastgo.model;

import com.alibaba.lava.base.LavaExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProfileSoftwareRelationDoExample extends LavaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public ProfileSoftwareRelationDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrifileCodeIsNull() {
            addCriterion("prifileCode is null");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeIsNotNull() {
            addCriterion("prifileCode is not null");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeEqualTo(String value) {
            addCriterion("prifileCode =", value, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeNotEqualTo(String value) {
            addCriterion("prifileCode <>", value, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeGreaterThan(String value) {
            addCriterion("prifileCode >", value, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeGreaterThanOrEqualTo(String value) {
            addCriterion("prifileCode >=", value, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeLessThan(String value) {
            addCriterion("prifileCode <", value, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeLessThanOrEqualTo(String value) {
            addCriterion("prifileCode <=", value, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeLike(String value) {
            addCriterion("prifileCode like", value, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeNotLike(String value) {
            addCriterion("prifileCode not like", value, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeIn(List<String> values) {
            addCriterion("prifileCode in", values, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeNotIn(List<String> values) {
            addCriterion("prifileCode not in", values, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeBetween(String value1, String value2) {
            addCriterion("prifileCode between", value1, value2, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andPrifileCodeNotBetween(String value1, String value2) {
            addCriterion("prifileCode not between", value1, value2, "prifileCode");
            return (Criteria) this;
        }

        public Criteria andRunServerIpIsNull() {
            addCriterion("runServerIp is null");
            return (Criteria) this;
        }

        public Criteria andRunServerIpIsNotNull() {
            addCriterion("runServerIp is not null");
            return (Criteria) this;
        }

        public Criteria andRunServerIpEqualTo(String value) {
            addCriterion("runServerIp =", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpNotEqualTo(String value) {
            addCriterion("runServerIp <>", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpGreaterThan(String value) {
            addCriterion("runServerIp >", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpGreaterThanOrEqualTo(String value) {
            addCriterion("runServerIp >=", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpLessThan(String value) {
            addCriterion("runServerIp <", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpLessThanOrEqualTo(String value) {
            addCriterion("runServerIp <=", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpLike(String value) {
            addCriterion("runServerIp like", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpNotLike(String value) {
            addCriterion("runServerIp not like", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpIn(List<String> values) {
            addCriterion("runServerIp in", values, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpNotIn(List<String> values) {
            addCriterion("runServerIp not in", values, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpBetween(String value1, String value2) {
            addCriterion("runServerIp between", value1, value2, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpNotBetween(String value1, String value2) {
            addCriterion("runServerIp not between", value1, value2, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeIsNull() {
            addCriterion("softwareCode is null");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeIsNotNull() {
            addCriterion("softwareCode is not null");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeEqualTo(String value) {
            addCriterion("softwareCode =", value, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeNotEqualTo(String value) {
            addCriterion("softwareCode <>", value, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeGreaterThan(String value) {
            addCriterion("softwareCode >", value, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeGreaterThanOrEqualTo(String value) {
            addCriterion("softwareCode >=", value, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeLessThan(String value) {
            addCriterion("softwareCode <", value, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeLessThanOrEqualTo(String value) {
            addCriterion("softwareCode <=", value, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeLike(String value) {
            addCriterion("softwareCode like", value, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeNotLike(String value) {
            addCriterion("softwareCode not like", value, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeIn(List<String> values) {
            addCriterion("softwareCode in", values, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeNotIn(List<String> values) {
            addCriterion("softwareCode not in", values, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeBetween(String value1, String value2) {
            addCriterion("softwareCode between", value1, value2, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareCodeNotBetween(String value1, String value2) {
            addCriterion("softwareCode not between", value1, value2, "softwareCode");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigIsNull() {
            addCriterion("softwareConfig is null");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigIsNotNull() {
            addCriterion("softwareConfig is not null");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigEqualTo(String value) {
            addCriterion("softwareConfig =", value, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigNotEqualTo(String value) {
            addCriterion("softwareConfig <>", value, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigGreaterThan(String value) {
            addCriterion("softwareConfig >", value, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigGreaterThanOrEqualTo(String value) {
            addCriterion("softwareConfig >=", value, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigLessThan(String value) {
            addCriterion("softwareConfig <", value, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigLessThanOrEqualTo(String value) {
            addCriterion("softwareConfig <=", value, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigLike(String value) {
            addCriterion("softwareConfig like", value, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigNotLike(String value) {
            addCriterion("softwareConfig not like", value, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigIn(List<String> values) {
            addCriterion("softwareConfig in", values, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigNotIn(List<String> values) {
            addCriterion("softwareConfig not in", values, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigBetween(String value1, String value2) {
            addCriterion("softwareConfig between", value1, value2, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andSoftwareConfigNotBetween(String value1, String value2) {
            addCriterion("softwareConfig not between", value1, value2, "softwareConfig");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "Id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "Id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "Id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "Id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "Id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("GMT_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("GMT_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("GMT_CREATE =", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("GMT_CREATE <>", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("GMT_CREATE >", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE >=", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("GMT_CREATE <", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE <=", value, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("GMT_CREATE in", values, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("GMT_CREATE not in", values, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE between", value1, value2, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE not between", value1, value2, "GmtCreate");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "Creator");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("GMT_MODIFIED is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("GMT_MODIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("GMT_MODIFIED =", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <>", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("GMT_MODIFIED >", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED >=", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("GMT_MODIFIED <", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <=", value, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("GMT_MODIFIED in", values, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("GMT_MODIFIED not in", values, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED between", value1, value2, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED not between", value1, value2, "GmtModified");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("MODIFIER =", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("MODIFIER <>", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("MODIFIER >", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIER >=", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("MODIFIER <", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("MODIFIER <=", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("MODIFIER in", values, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("MODIFIER not in", values, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("MODIFIER between", value1, value2, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("MODIFIER not between", value1, value2, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("MODIFIER like", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("MODIFIER not like", value, "Modifier");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("IS_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("IS_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("IS_DELETED =", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("IS_DELETED <>", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("IS_DELETED >", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETED >=", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("IS_DELETED <", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETED <=", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("IS_DELETED in", values, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("IS_DELETED not in", values, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("IS_DELETED between", value1, value2, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("IS_DELETED not between", value1, value2, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("IS_DELETED like", value, "IsDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("IS_DELETED not like", value, "IsDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 28 15:22:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_profile_software_relation
     *
     * @mbg.generated Tue Jul 28 15:22:00 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}